#!/bin/bash
# if "false" output contains only error-messages, otherwise as well informational messages (success of actions)
verbose=true

# define remote hosts if you want
# xyz=""
fawe="fahrradwerkstatt.homelinux.org"
rage="radgeber.homelinux.org"
kos2="pc2-kos2.physchem.uni-freiburg.de"
uni="pc2-77.physchem.uni-freiburg.de"

# automatic definition of localhost
localhost=$(hostname --fqdn)

# set backup directory path
bu_path='/home/backup'

# set path to the exclude files; defaults to this directory
exclude_path=$(dirname $0)
global_excludes="$exclude_path/exclude-global"

# check backup disk for necessary free space [%]
check_minimal_disk_space=true
hd_minfree_percent=20

# mount backup partition read only after backup?
mount_ro=true

# Host settings
name=$1
ssh_port=22
case "$name" in
	# NAME)
	# 	from_host= 	# FQDN even if it's localhost
	# 	to_host= 	# s.a.
	# 	ssh_port=       # optional
	# 	;;
	rage)
		from_host=$rage
		to_host=$fawe
		ssh_port=175
		;;
	fawe)
		from_host=$fawe
		to_host=$rage
		ssh_port=175
		;;
	uni)
		from_host=$uni
		to_host=$kos2
		;;
	*)	message "" "Host '$name' is not known!!!" "FATAL" ;;
esac

# default settings, override each value in the following case statement
task=$2
bu_dir="/$bu_path/$name/$task"
excludes="$exclude_path/exclude-$task"
rsync_log="/var/log/backup/${name}_${task}.log"
rsync_opts=""
case "$task" in
	# NAME)
	# 	from_path= 	# backup src directory 
	# 	bu_dir= 	# optional, backup dest directory on backup_host
	# 	excludes= 	# optional, exclude file for the job
	# 	rsync_opts= 	# optional
	# 	;;
	daten)
		from_path="/home"
		rsync_opts="-x"
		;;
	system)
		from_path="/"
		rsync_opts=""
		;;
	postgres)
		from_path="/var/lib/postgresql/db_dumps"
		rsync_opts="-x"
		;;
	test)
		from_path="/home/widu/bu-test"
		rsync_opts="-x"
		;;
	*)	message "" "task $2 is not known!!!" "FATAL" ;;
esac

